[package]
name = "nessie"
description = "A code scoring tool for deno"
repository = "https://github.com/denosaurs/nessie"
license = "MIT"
version = "0.1.0"
authors = ["Elias Sjögreen", "Filippo Rossi"]
edition = "2018"
publish = false

[dependencies]
deno_lint = { version = "0.1.10", git = "https://github.com/denoland/deno_lint" }
serde = "1.0.111"
termcolor = "1.1.0"
walkdir = "2.3.1"
regex = "1.3.9"
