[package]
name = "nessie"
description = "A code scoring tool for deno"
repository = "https://github.com/denosaurs/nessie"
license = "MIT"
version = "0.1.0"
authors = ["Elias Sjögreen", "Filippo Rossi"]
edition = "2018"
publish = false

[dependencies]
